version: '3'
services:
   ngnix:
     restart: always
     image: vponnap/welcometofebatecheks:1
     container_name: nginxctr
     ports:
       - "14256:443"
       - "14243:80"
     volumes:
      - /var/lib/docker/volumes/nginxhome/_data:/data/db
