apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      # Port accessible inside cluster
      port: 80
       # Port to forward to inside the pod
      targetPort: 80
      # Port accessible outside cluster
      nodePort: 30005
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30006
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deplmnt
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginxcntr
        image: vponnap/welcometofebatecheks:1
        ports:
        - containerPort: 80
